# Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Minecraft / Fabric
minecraft_version=26.1
target_label=26.x
minecraft_dependency=>=26.1 <27
loader_version=0.18.4
loader_min_version=0.18.4
loom_version=1.17.19
fabric_api_version=0.145.1+26.1
fabric_api_min_version=0.145.1

# Mod metadata
upstream_mod_version=2.7.1.351
port_version=6
maven_group=info.u-team
